### ISSUE TITLE
Syncing is really slow

### ISSUE THREAD

**Issue by daniiba** [aiblocks/AiBlocks#1]
Syncing is really slow, blocks are created almost as fast as the syncing process takes to process the old ones. Any idea why?

**Comment by thuphan64** [comment]
The AiBlocks network is currently being attacked by a flood attack that we are working hard to create a block for. In the meanwhile, users may experience issues connecting.

Thank you all for you patience.

**Comment by thuphan64** [comment]
Solved in version 0.124a
